apiVersion: v1
kind: Pod
metadata:
  labels:
      test: liveness
  name: aws-cli
spec:
  containers:
  - name: aws-cli
    image: ohben/aws-cli
    resources:
     limits:
      memory: "2048Mi"
     requests:
      memory: "2048Mi"
    command: [ "sleep", "1200" ]
