apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
spec:
  containers:
  - name: aws-cli
    image: ohben/aws-cli
    resources:
     limits:
      memory: "1024Mi"
     requests:
      memory: "512Mi"
    command: [ "sleep", "600" ]
